title: Romina Mahinpei
logo: /assets/images/headshot_square.png
description: > 
  MSE Student @ Princeton CS
  <br><br> 
  I am a fully-funded Master of Science & Engineering (M.S.E.) student in the Computer Science department at Princeton University. 
  I received a Bachelor's of Science (B.S.) degree in Honours Computer Science along with a Mathematics Minor at The University of British Columbia. 
  My current research intersts include <b>high performance computing, human-centred AI, and computer science education</b>. 
  
  <br><br>
  <a href="mailto:romina.mahinpei@yahoo.com">Email</a> | <a href="assets/files/CV.pdf">CV</a> | <a href="https://www.linkedin.com/in/romina-mahinpei/">LinkedIn</a> | <a href="https://github.com/rmahinpei">GitHub</a> 

show_downloads: false
theme: jekyll-theme-minimal