title: Romina Mahinpei
logo: /assets/images/headshot_square.png
description: > 
  <a href="mailto:romina.mahinpei@yahoo.com">Email Me</a>
  <br>
  <a href="https://www.linkedin.com/in/romina-mahinpei/">View my LinkedIn Profile</a>

show_downloads: false
theme: jekyll-theme-minimal