title: Romina Mahinpei
logo: /assets/images/headshot_square.png
description: > 
  <a href="mailto:romina.mahinpei@yahoo.com">Email</a> | <a href="assets/files/CV.pdf">CV</a> | <a href="https://www.linkedin.com/in/romina-mahinpei/">LinkedIn</a> | <a href="https://github.com/rmahinpei">GitHub</a> 

show_downloads: false
theme: jekyll-theme-minimal